### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by agonbina** [avinoamr/blueprint.js#1]
Hey @avinoamr, I really like the idea behind blueprint.js!

I see there are a few things under "work in progress" but there hasn't been any development since June of last year, so I was just wondering if you are planning to continue development?

Best,
Agon

**Comment by avinoamr** [comment]
Hey @agonbina , thanks. I've decided to reconsider the whole thing, because when I tried it on some large-scale production code, the result was way too verbose for my taste. I'm now leaning towards an API that is more limited to a set of decoration functions.

**Comment by agonbina** [comment]
I see. I will just move on to the new ES6 class :)

**Comment by avinoamr** [comment]
Perfect. Good luck :)
